toc:
  - name: Sotez
    file: docs/sotez.md

  - name: Key
    file: docs/key.md

  - name: Crypto
    file: docs/crypto.md

  - name: Forge
    file: docs/forge.md

  - name: Ledger
    file: docs/ledger.md

  - name: Utility
    file: docs/utility.md
