// flow-typed signature: 09cfe36e36d17851beb9a2dccff30797
// flow-typed version: <<STUB>>/bip39_v^3.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bip39'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bip39' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bip39/src/_wordlists' {
  declare module.exports: any;
}

declare module 'bip39/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bip39/src/_wordlists.js' {
  declare module.exports: $Exports<'bip39/src/_wordlists'>;
}
declare module 'bip39/src/index.js' {
  declare module.exports: $Exports<'bip39/src/index'>;
}
