// flow-typed signature: 14e8f31ba56aeed2beb98b2764f862a5
// flow-typed version: <<STUB>>/blake2b_v^2.1.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blake2b'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blake2b' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blake2b/example' {
  declare module.exports: any;
}

declare module 'blake2b/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blake2b/example.js' {
  declare module.exports: $Exports<'blake2b/example'>;
}
declare module 'blake2b/index' {
  declare module.exports: $Exports<'blake2b'>;
}
declare module 'blake2b/index.js' {
  declare module.exports: $Exports<'blake2b'>;
}
declare module 'blake2b/test.js' {
  declare module.exports: $Exports<'blake2b/test'>;
}
