// flow-typed signature: 83d15fe1972bd93e77ce82d8d4ab6579
// flow-typed version: <<STUB>>/bs58check_v^2.1.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs58check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs58check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs58check/base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs58check/base.js' {
  declare module.exports: $Exports<'bs58check/base'>;
}
declare module 'bs58check/index' {
  declare module.exports: $Exports<'bs58check'>;
}
declare module 'bs58check/index.js' {
  declare module.exports: $Exports<'bs58check'>;
}
