// flow-typed signature: c2f29e6a0ed6915eb0c76f04cb0a32b7
// flow-typed version: <<STUB>>/detect-node_v^2.0.4/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detect-node/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detect-node/browser.js' {
  declare module.exports: $Exports<'detect-node/browser'>;
}
declare module 'detect-node/index' {
  declare module.exports: $Exports<'detect-node'>;
}
declare module 'detect-node/index.js' {
  declare module.exports: $Exports<'detect-node'>;
}
