// flow-typed signature: 39450e9a0efc6ef70cbbead0578b611e
// flow-typed version: <<STUB>>/libsodium-wrappers_v^0.7.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libsodium-wrappers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libsodium-wrappers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libsodium-wrappers/dist/modules/libsodium-wrappers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libsodium-wrappers/dist/modules/libsodium-wrappers.js' {
  declare module.exports: $Exports<'libsodium-wrappers/dist/modules/libsodium-wrappers'>;
}
