// flow-typed signature: bbf8b00d093f1a39d95541315953f59c
// flow-typed version: <<STUB>>/remove-flow-types-loader_v^1.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-flow-types-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-flow-types-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remove-flow-types-loader/index' {
  declare module.exports: $Exports<'remove-flow-types-loader'>;
}
declare module 'remove-flow-types-loader/index.js' {
  declare module.exports: $Exports<'remove-flow-types-loader'>;
}
