// flow-typed signature: d3340e1f3843e9e4a6567b095f28f7d7
// flow-typed version: <<STUB>>/secp256k1_v^3.7.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'secp256k1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'secp256k1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'secp256k1/bindings' {
  declare module.exports: any;
}

declare module 'secp256k1/elliptic' {
  declare module.exports: any;
}

declare module 'secp256k1/js' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/assert' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/der' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/elliptic/index' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/index' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/js/bn/index' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/js/bn/optimized' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/js/ecjpoint' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/js/ecpoint' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/js/ecpointg' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'secp256k1/bindings.js' {
  declare module.exports: $Exports<'secp256k1/bindings'>;
}
declare module 'secp256k1/elliptic.js' {
  declare module.exports: $Exports<'secp256k1/elliptic'>;
}
declare module 'secp256k1/index' {
  declare module.exports: $Exports<'secp256k1'>;
}
declare module 'secp256k1/index.js' {
  declare module.exports: $Exports<'secp256k1'>;
}
declare module 'secp256k1/js.js' {
  declare module.exports: $Exports<'secp256k1/js'>;
}
declare module 'secp256k1/lib/assert.js' {
  declare module.exports: $Exports<'secp256k1/lib/assert'>;
}
declare module 'secp256k1/lib/der.js' {
  declare module.exports: $Exports<'secp256k1/lib/der'>;
}
declare module 'secp256k1/lib/elliptic/index.js' {
  declare module.exports: $Exports<'secp256k1/lib/elliptic/index'>;
}
declare module 'secp256k1/lib/index.js' {
  declare module.exports: $Exports<'secp256k1/lib/index'>;
}
declare module 'secp256k1/lib/js/bn/index.js' {
  declare module.exports: $Exports<'secp256k1/lib/js/bn/index'>;
}
declare module 'secp256k1/lib/js/bn/optimized.js' {
  declare module.exports: $Exports<'secp256k1/lib/js/bn/optimized'>;
}
declare module 'secp256k1/lib/js/ecjpoint.js' {
  declare module.exports: $Exports<'secp256k1/lib/js/ecjpoint'>;
}
declare module 'secp256k1/lib/js/ecpoint.js' {
  declare module.exports: $Exports<'secp256k1/lib/js/ecpoint'>;
}
declare module 'secp256k1/lib/js/ecpointg.js' {
  declare module.exports: $Exports<'secp256k1/lib/js/ecpointg'>;
}
declare module 'secp256k1/lib/js/index.js' {
  declare module.exports: $Exports<'secp256k1/lib/js/index'>;
}
