// flow-typed signature: ee007ae7545e112edd0c1addbcfd5e95
// flow-typed version: <<STUB>>/unminified-webpack-plugin_v^2.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unminified-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unminified-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'unminified-webpack-plugin/index' {
  declare module.exports: $Exports<'unminified-webpack-plugin'>;
}
declare module 'unminified-webpack-plugin/index.js' {
  declare module.exports: $Exports<'unminified-webpack-plugin'>;
}
